### ISSUE TITLE
Unit ambiguity: 'm'

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#15]
If a unit is specified to be 'm' could mean minutes or metres.

I recommend disallowing minutes as a unit for this reason.

Thoughts?

**Comment by Ichoran** [comment]
The Scala reference implementation allows "minute" and "min" as abbrevations for minute, but doesn't allow "m".  However, if we really want to avoid problems, we should not just disallow minutes _but disallow `m`_.

In that case, if you want meters, you will have to say so in full, unless you couple them with SI units (which is basically never done with minutes, so it's an indication that it's meters).  So `cm` would be cool, as is `min`, but `m` is out due to ambiguity.

**Comment by MichaelCurrie** [comment]
In my opinion we would cause more trouble than we would save to force people to write out `meter` or `metre`, because:
1. There is likely widespread use of `cm` and `m`, etc,
2. Right now we allow any prefix with any suffix, so it would be a shame to have to have to break that simplicity to allow `cm` but not `cmin` (although as you say that's in practice very rarely done)

Instead, I'll just follow your Scala reference implementation and not allow `m` for minutes.

Feel free to reopen this if you feel otherwise and I'll go with disallowing `m` as well.
