### ISSUE TITLE
Scala implementation is not validated on every PR.

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#35]
The Travis CI job should run the Scala implementation against all test files.

**Comment by Ichoran** [comment]
@MichaelCurrie - Travis kind of sucks at multi-language projects in its nice set-things-up-for-you scripts only work for a single language, so you have to do the installations yourself for all languages past the first.

One idea would be, since Scala looks to be the hardest to install, to set the language to Scala, then install Python and possibly Julia by hand.  But then the feature matrix is going to be a little wonky.

An alternate idea is to decide that only Python's getting CI treatment.  But then the Python ought to validate the WCON_format.md examples.  (Then one is responsible for running sbt test before checking in a Scala PR, and similarly for Julia etc..)

Or we could try using different CI services for different languages.  Kind of weird, but ironically it might be the simplest and best solution.

Thoughts?

**Comment by MichaelCurrie** [comment]
I like your first idea.

From [Tomas Zezula's blog](http://zezutom.blogspot.ca/2015/02/travis-ci-and-multi-language-projects.html) and [this conversation on Travis-CI's GitHub site](https://github.com/travis-ci/travis-ci/issues/538), it seems like one approach would be to use Python as the "master" language but then within the test `.travis.yml` script, install Scala, Julia, etc, and run their tests as well:

```
language: python

before_install:
    - sudo apt-get update
    - sudo apt-get install scala

script:
    - "./whatever/you/run/tests/with"
```

I've got the Python test suite checking all the JSON snippets in the .MD files as per issue #34.  If you want to add testing for Scala, etc, and I agree it would be great to give it the full "CI treatment" as you say, I think the above would be the simplest approach.

I agree that this makes the feature matrix wonky.  Maybe we only test if `$TRAVIS_PYTHON_VERSION == 2.7` so that the scala tests don't get run three times (for every Python version being tested (2.7, 3.4, and 3.5).)

**Comment by Ichoran** [comment]
Python is easier to install than Scala, because everything in Scala is built with SBT, but Linux distributions generally don't package SBT.  Also, Scala + dependencies is a bigger download than Python, so it's less efficient.  So if we go with multiple languages, it should almost certainly be Scala by default with others added.  (Unless others are supported by Travis and even harder to correctly install.)

I'm just not convinced that this is the way to go as opposed to multiple different CI services.

**Comment by MichaelCurrie** [comment]
In that case I'm happy to go along with the approach you decide here; even if it means subordinating Python within the Travis CI file that's no problem, or perhaps going with multiple CI services.  Let me know if you need anything from me.

**Comment by Ichoran** [comment]
I'm going to try a second CI service.  I like how well the Python feature matrix works, so I'd rather just leave the current CI alone.  If we don't have CI for Scala, I don't think it's a disaster; the protocol can just be "run sbt test before you check in".  It will occasionally get forgotten, but it's not that big a burden.  (It only takes a few seconds.)

**Comment by Ichoran** [comment]
Resolved by testing Scala with Semaphore CI.  Build status tag delivered via https://github.com/openworm/tracker-commons/pull/56
