### ISSUE TITLE
Specification does not describe units for cx, cy, ox, oy

### ISSUE THREAD

**Issue by Ichoran** [openworm/tracker-commons#54]
The specification states that x and y units must be given, and it is natural to assume that unless stated otherwise, cx, cy, ox, and oy, if present, will have the same units.  However, one might also assume that this implicit assumption should be made explicit.

The implementations are not consistent: Scala assumes inheritance for all four, while Python requires units at least on cx and cy.

The implementations should be made consistent, and the documentation should be updated to reflect which behavior is correct.

@MichaelCurrie - Which way do you think we should go?  (You can see which way I thought before given how Scala turned out, but maybe you have reasons to prefer the other behavior?)

**Comment by MichaelCurrie** [comment]
My preference is that it be an explicit requirement and not derived from "x", "y".  Because:
1. I think if someone is going to go to the length of using the "cx", "cy", "ox", "oy" feature of the WCON format, I believe it's not too much of an imposition that they include the line `"cx": "mm"`, etc.
2. Deriving units means we are then making an assumption about the units of their data, and given the low cost of forcing the authors to make their units explicit, it seems like an assumption we don't need to be making.
3. [The specification](https://github.com/openworm/tracker-commons/blob/master/WCON_format.md) states:

> Any numeric quantity followed on a per-animal or per-timepoint basis must have its units defined in an object

If you agree, we'd just have to drop the line:

> Units must be specified at least for "t", "x", and "y".

This line already somewhat contradicts the previous quoted line.

**Comment by Ichoran** [comment]
@aexbrown - Do you have an opinion here?

**Comment by aexbrown** [comment]
I would prefer to force users to define units in each case for the sake of consistency.  I agree it’s natural to assume the units would be the same, but better not to make the assumption.

**Comment by Ichoran** [comment]
Let's do it that way, then.

@michaelcurrie - Can you check if the Python implementation will require any changes?

**Comment by MichaelCurrie** [comment]
I don't believe the Python implementation will require any changes, since any elements used without defined units cause an error to be raised.

Incidentally, it also raises an error if `cx` is defined for a segment but not `cy`, for instance.  I hope that's a reasonable thing - if people want to define only the y-axis of the centroid or origin they can just declare the x-axis to be 0 in all frames.

**Comment by Ichoran** [comment]
I think that's reasonable.

**Comment by Ichoran** [comment]
Should be resolved by https://github.com/openworm/tracker-commons/pull/58

**Comment by MichaelCurrie** [comment]
Resolved by #58
