### ISSUE TITLE
Write unit tests to validate readers

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/tracker-commons#6]
One test could be some simple data, and test that after using the reader and then the writer, diffing the original and output files reveals no difference.

**Comment by Ichoran** [comment]
I just emailed Andre something similar:

I've done some work on an implementation of the spec, but it occurs to me that there are not any complete example files.  This makes it a bit difficult to test whether my implementation is working.

I think we should have three (four):
1. minimal.wcon
   A file that has data that has the absolute minimum number of elements needed to be valid--that is, a minimal writing program must be able to at least write this.
2. minimax.wcon
   A file that uses every single basic feature--that is, a minimal reading program must correctly get the data from this.
3. maximal_1.wcon, maximal_2.wcon
   File(s) that use every extended feature of the specification, so that everything we talk about in the specification has at least one example.  (Since we specify how to deal with multiple files, I guess there must be two of these.)

**Comment by Ichoran** [comment]
@MichaelCurrie - Do you want to try your hand at writing the files based on Andre's specification?  I can then check whether my Scala reader reads/writes them without (substantive) changes.

You do want a JSON-aware diff, as whitespace changes ought not be considered significant, nor (probably) the order in which key-value pairs are presented.

**Comment by MichaelCurrie** [comment]
In addition to the pull request mentioned above, I also added Travis CI for "continuous integration" testing of all pull requests and pushes affecting the Python code.

It may also be possible to extend this to allow for testing of the code written in other languages, but I haven't looked into this.

I think once the pull request is merged we can close this issue for now.

**Comment by Ichoran** [comment]
Travis CI is a great addition.  I'll hook in the other languages' tests when I have time (assuming I can figure out how with all of them; I know Scala will work, but I've never looked into it for Julia).

**Comment by MichaelCurrie** [comment]
Handled by 2b35d01e7f0ea46b8e311d7218bfab38670900eb
