### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by cheelee** [openworm/tracker-commons#61]
I just noticed that `wcon/wcon_data.py` invokes `time.monotonic()` which is not compatible with Python 2, at least as far as the official APIs go.

This was borne out on my Mac, where I had to switch to a Python 3 environment in order to run `temp_example.py` successfully. I'm just checking to see if we intend to support Python 2 in our code base.

**Comment by MichaelCurrie** [comment]
Good catch.  The commit that introduced the two lines that use `time.monotonic()`:

![image](https://cloud.githubusercontent.com/assets/5267078/13646948/06b316a0-e5ef-11e5-8d7f-2b494bffadfa.png)

...should have been on the `python_speedfix` branch.  Basically it's just temporary profiling code.  On that branch those lines have since been removed.  Travis CI runs a battery of tests on Python 2.7 and on that branch it's passing.  Normally we have Python 2 support.  As soon as [this pull request](https://github.com/openworm/tracker-commons/pull/60) is accepted we'll be back.

**Comment by MichaelCurrie** [comment]
This is fixed by PR #77
